[kDocument1]
delete = true
path = "/SDCARD/vision/face_recognition/age/tinyage_gray_112_age_gender_sim.onnx"

[kDocument2]
delete = true
path = "/SDCARD/vision/face_recognition/detect/mnetv2_gray_nop_light_epoch_235_512.onnx"

[kDocument3]
delete = true
path = "/SDCARD/vision/face_recognition/emotion/speaker_v5_island_v4_data3_sim.onnx"

[kDocument4]
delete = true
path = "/SDCARD/vision/face_recognition/feature/airfacenet_v1.onnx"

[kDocument5]
delete = true
path = "/SDCARD/vision/face_recognition/landmark/groupdiv128a_vis_uncertain_sim.onnx"
